title: Luca Dall'Asta
description: Associate Professor of Theoretical Physics & Complex Systems
remote_theme: "mmistakes/minimal-mistakes@master"
minimal_mistakes_skin: "air" # Opzioni eleganti: air, mint, dirt, sunrise, contrast

# Impostazioni Layout
sidebar:
  nav: "main"

header_pages:
  - index.md
  - research.md
  - publications.md
  - teaching.md
